
#Eureka server uses this application name as service id for this department service
spring.application.name=API-GATEWAY
server.port=9191
#to make this department service register with eureka server we need to provide eureka server url
eureka.instance.client.serverUrl.defaultZone=http://localhost:8761/eureka/

management.endpoints.web.exposure.include=*

#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true
#logging.level.org.springframework.cloud.gateway=DEBUG


#Routes for Employee service
#this is the server id of Employee service in Eureka server
spring.cloud.gateway.routes[0].id=EMPLOYEE-SERVICE
#As the API Gateway supports load balancing, we can use below rul
spring.cloud.gateway.routes[0].uri=lb://EMPLOYEE-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/employees/**

#Routes for Department service
#this is the server id of Employee service in Eureka server
spring.cloud.gateway.routes[1].id=DEPARTMENT-SERVICE
#As the API Gateway supports load balancing, we can use below rul
spring.cloud.gateway.routes[1].uri=lb://DEPARTMENT-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/departments/**

#Routes for Organization service
#this is the server id of Organization service in Eureka server
spring.cloud.gateway.routes[2].id=ORGANIZATION-SERVICE
#As the API Gateway supports load balancing, we can use below rul
spring.cloud.gateway.routes[2].uri=lb://ORGANIZATION-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/organizations/**


spring.zipkin.baseUrl=http://localhost:9411

zipkin.storage.type=elasticsearch
zipkin.storage.elasticsearch.hosts=http://localhost:9200
zipkin.storage.elasticsearch.retention=7
spring.sleuth.sampler.probability=0.1



