#
#spring.datasource.driver.class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/department_db
#spring.datasource.username=postgres
#spring.datasource.password=root
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
##Eureka server uses this application name as service id for this department service
spring.application.name=DEPARTMENT-SERVICE
#We kept all the configurations of department service in git repository, and to fetch all those
#configration we need to add the below property to make configuration server fetch all the configurations
# of department service
spring.config.import=optional:configserver:http://localhost:8888
management.endpoints.web.exposure.include=*
##to make this department service register with eureka server we need to provide eureka server url
#eureka.instance.client.serverUrl.defaultZone=http://localhost:8761/eureka/

#These are the default values for rabbitmq server to run our machine

#This is the host name, as we are running on our machine, it will be localhost
spring.rabbitmq.host=localhost

#The default port of the localhost is 5672
spring.rabbitmq.port=5672

#Default username and password
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.zipkin.baseUrl=http://localhost:9411