##spring.application.name=employee-service
#spring.datasource.driver.class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/employee_db
#spring.datasource.username=postgres
#spring.datasource.password=root
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#server.port=8081
#
##Eureka server uses this application name as service id for this employee service
spring.application.name=EMPLOYEE-SERVICE
#We kept all the configurations of department service in git repository, and to fetch all those
#configration we need to add the below property to make configuration server fetch all the configurations
# of department service
spring.config.import=optional:configserver:http://localhost:8888
##to make this employee service register with eureka server we need to provide eureka server url
#eureka.instance.client.serverUrl.defaultZone=http://localhost:8761/eureka/


#This is the host name, as we are running on our machine, it will be localhost
spring.rabbitmq.host=localhost

#The default port of the localhost is 5672
spring.rabbitmq.port=5672

#Default username and password
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.zipkin.baseUrl=http://localhost:9411

#Acutuator end points for circute breaker
management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

#circute breaker configuration
resilience4j.circuitbreaker.instances.EMPLOYEE-SERVICE.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.EMPLOYEE-SERVICE.failureRateThreshold=50
resilience4j.circuitbreaker.instances.EMPLOYEE-SERVICE.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.EMPLOYEE-SERVICE.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.EMPLOYEE-SERVICE.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.EMPLOYEE-SERVICE.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.EMPLOYEE-SERVICE.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.EMPLOYEE-SERVICE.slidingWindowSize=10

#Retry configuration
resilience4j.retry.instances.EMPLOYEE-SERVICE.registerHealthIndicator=true
resilience4j.retry.instances.EMPLOYEE-SERVICE.maxRetryAttempts=5
resilience4j.retry.instances.EMPLOYEE-SERVICE.waitDuration=2s









